spring.application.name=projeto
server.servlet.context-path=/projeto
spring.datasource.url=jdbc:mysql://localhost:3306/clube
spring.datasource.username=user
spring.datasource.password=Laranja10@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mvc.format.default-content-type=application/json
spring.mvc.format.ignore-accept-header=true


